name: Call My Cron URL

on:
  schedule:
    - cron: '*/20 * * * *'  # Chạy mỗi 10 phút (theo UTC)
  workflow_dispatch:         # Cho phép chạy tay

jobs:
  call-url:
    runs-on: ubuntu-latest
    steps:
      - name: Gọi URL
        run: curl -sL https://white-smoke-d789.quynhnguyen291190.workers.dev
